import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PublicNavbar from "./components/nav/publicNavbar";
import Footer from "./components/nav/footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional for Tailwind integration
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable} antialiased bg-[#FAFAFA] text-[#111111]`}>
        
        {/* 🔥 Shared Navbar (will appear on every page) */}
        <PublicNavbar />

        {/* Page content */}
        <main className="min-h-screen">
          {children}
          <Toaster position="top-right" />
        </main>

        {/* Footer */}
        <Footer />

      </body>
    </html>
  );
}
